PCRE2 compatibility (#587)
* Fix: use pcre2 when building with nginx >= 1.21.5

I've tried to compile naxsi 1.3 as module for nginx 1.21.6, and got the error:

error: invalid use of incomplete typedef 'ngx_regex_t' {aka 'struct pcre2_real_code_8'}
  205 |       (tmp_idx < len && (match = pcre_exec(rl->br->rx->regex->code,

I found this issue report: Ref: https://github.com/nbs-system/naxsi/issues/580
then i tried to solve the pcre2 compatibility issue.

I've included an helper function that is 'copied' from: https://github.com/nginx/nginx/blob/master/src/core/ngx_regex.c#L393
that it is called in place of 'pcre_exec' when nginx_version >= 1021005

Not sure if this is the best solution, but I managed to build naxsi 1.3 as module for nginx 1.21.6 succesfully, and it seems to work well.

I'm not used to develop in C anymore (since 25 years ago, at least!), but I hope that this patch I made can help anybody else.

* Added a check for nginx_version >= 1021005

Added a check for nginx_version >= 1021005 to avoid helper function definition on older versions

* Use NGX_PCRE2 conditional

Update naxsi.h

Don't include pcre.h in order for compilation to work both against pcre and pcre2

Fix pcre vs pcre2 compilation

Co-authored-by: laluigino <99279306+laluigino@users.noreply.github.com>